sudo: required

services:
  - docker

before_install:
  - deploy/dockerize.sh master test
  - docker pull mysql
  - docker pull elasticsearch:2.2.0
  - docker run --rm -d --e MYSQL_ROOT_PASSWORD=root -n mysql mysql
  - docker run --rm -d -n elastic elasticsearch:2.2.0

script:
  - docker run --rm --link mysql:mysql --link elastic:elastic docker.coneda.net/kor:master bundle exec rake db:test:load
  - docker run --rm --link mysql:mysql --link elastic:elastic docker.coneda.net/kor:master bundle exec rspec spec
  - docker run --rm --link mysql:mysql --link elastic:elastic -e HEADLESS=true docker.coneda.net/kor:master bundle exec cucumber features
